//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Android/FoodTruckr/app/src/main/java/com/brianjmelton/foodtruckr/shared/detail/RestaurantDetailDispatch.java
//

#ifndef _ComBrianjmeltonFoodtruckrSharedDetailRestaurantDetailDispatch_H_
#define _ComBrianjmeltonFoodtruckrSharedDetailRestaurantDetailDispatch_H_

#import "JreEmulation.h"

@protocol ComBrianjmeltonFoodtruckrSharedDetailRestaurantDetailDispatch < NSObject, JavaObject >

- (void)onDisplayNameWithLong:(jlong)id_;

- (void)onDisplayLogoWithLong:(jlong)id_;

- (void)onDisplayLinkWithLong:(jlong)id_;

- (void)onDisplayCuisineWithLong:(jlong)id_;

- (void)onDisplayPaymentWithLong:(jlong)id_;

- (void)onDisplayShortDescriptionWithLong:(jlong)id_;

- (void)onDisplayLongDescriptionWithLong:(jlong)id_;

@end

__attribute__((always_inline)) inline void ComBrianjmeltonFoodtruckrSharedDetailRestaurantDetailDispatch_init() {}

#endif // _ComBrianjmeltonFoodtruckrSharedDetailRestaurantDetailDispatch_H_
