//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Android/FoodTruckr/app/src/main/java/com/brianjmelton/foodtruckr/shared/detail/RestaurantDetailDispatch.java
//

#include "com/brianjmelton/foodtruckr/shared/detail/RestaurantDetailDispatch.h"

@interface ComBrianjmeltonFoodtruckrSharedDetailRestaurantDetailDispatch : NSObject
@end

@implementation ComBrianjmeltonFoodtruckrSharedDetailRestaurantDetailDispatch

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "onDisplayNameWithLong:", "onDisplayName", "V", 0x401, NULL },
    { "onDisplayLogoWithLong:", "onDisplayLogo", "V", 0x401, NULL },
    { "onDisplayLinkWithLong:", "onDisplayLink", "V", 0x401, NULL },
    { "onDisplayCuisineWithLong:", "onDisplayCuisine", "V", 0x401, NULL },
    { "onDisplayPaymentWithLong:", "onDisplayPayment", "V", 0x401, NULL },
    { "onDisplayShortDescriptionWithLong:", "onDisplayShortDescription", "V", 0x401, NULL },
    { "onDisplayLongDescriptionWithLong:", "onDisplayLongDescription", "V", 0x401, NULL },
  };
  static const J2ObjcClassInfo _ComBrianjmeltonFoodtruckrSharedDetailRestaurantDetailDispatch = { "RestaurantDetailDispatch", "com.brianjmelton.foodtruckr.shared.detail", NULL, 0x201, 7, methods, 0, NULL, 0, NULL};
  return &_ComBrianjmeltonFoodtruckrSharedDetailRestaurantDetailDispatch;
}

@end

