//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Android/FoodTruckr/app/src/main/java/com/brianjmelton/foodtruckr/shared/detail/RestaurantDetailDelegate.java
//

#include "com/brianjmelton/foodtruckr/shared/detail/RestaurantDetailDelegate.h"

@interface ComBrianjmeltonFoodtruckrSharedDetailRestaurantDetailDelegate : NSObject
@end

@implementation ComBrianjmeltonFoodtruckrSharedDetailRestaurantDetailDelegate

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "onRestaurantDetailShownWithLong:", "onRestaurantDetailShown", "V", 0x401, NULL },
  };
  static const J2ObjcClassInfo _ComBrianjmeltonFoodtruckrSharedDetailRestaurantDetailDelegate = { "RestaurantDetailDelegate", "com.brianjmelton.foodtruckr.shared.detail", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_ComBrianjmeltonFoodtruckrSharedDetailRestaurantDetailDelegate;
}

@end

