//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Android/FoodTruckr/app/src/main/java/com/brianjmelton/foodtruckr/shared/detail/RestaurantDetailDelegate.java
//

#ifndef _ComBrianjmeltonFoodtruckrSharedDetailRestaurantDetailDelegate_H_
#define _ComBrianjmeltonFoodtruckrSharedDetailRestaurantDetailDelegate_H_

#import "JreEmulation.h"

@protocol ComBrianjmeltonFoodtruckrSharedDetailRestaurantDetailDelegate < NSObject, JavaObject >

- (void)onRestaurantDetailShownWithLong:(jlong)id_;

@end

__attribute__((always_inline)) inline void ComBrianjmeltonFoodtruckrSharedDetailRestaurantDetailDelegate_init() {}

#endif // _ComBrianjmeltonFoodtruckrSharedDetailRestaurantDetailDelegate_H_
