//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Android/FoodTruckr/app/src/main/java/com/brianjmelton/foodtruckr/shared/vo/Restaurant.java
//

#include "com/brianjmelton/foodtruckr/shared/vo/Restaurant.h"
#include "java/lang/StringBuilder.h"

@implementation ComBrianjmeltonFoodtruckrSharedVoRestaurant

- (NSString *)getName {
  return name_;
}

- (void)setNameWithNSString:(NSString *)name {
  self->name_ = name;
}

- (jlong)getId {
  return id__;
}

- (void)setIdWithLong:(jlong)id_ {
  self->id__ = id_;
}

- (NSString *)getLogo {
  return logo_;
}

- (void)setLogoWithNSString:(NSString *)logo {
  self->logo_ = logo;
}

- (NSString *)getBackground {
  return background_;
}

- (void)setBackgroundWithNSString:(NSString *)background {
  self->background_ = background;
}

- (NSString *)getLink {
  return link_;
}

- (void)setLinkWithNSString:(NSString *)link {
  self->link_ = link;
}

- (NSString *)getCuisine {
  return cuisine_;
}

- (void)setCuisineWithNSString:(NSString *)cuisine {
  self->cuisine_ = cuisine;
}

- (NSString *)getPayment {
  return payment_;
}

- (void)setPaymentWithNSString:(NSString *)payment {
  self->payment_ = payment;
}

- (NSString *)getShortDescription {
  return shortDescription_;
}

- (void)setShortDescriptionWithNSString:(NSString *)shortDescription {
  self->shortDescription_ = shortDescription;
}

- (NSString *)getLongDescription {
  return longDescription_;
}

- (void)setLongDescriptionWithNSString:(NSString *)longDescription {
  self->longDescription_ = longDescription;
}

- (NSString *)description {
  JavaLangStringBuilder *sb = [[JavaLangStringBuilder alloc] initWithNSString:@"Restaurant{"];
  (void) [((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([sb appendWithNSString:@"name='"])) appendWithNSString:name_])) appendWithChar:'\''];
  (void) [((JavaLangStringBuilder *) nil_chk([sb appendWithNSString:@", id="])) appendWithLong:id__];
  (void) [((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([sb appendWithNSString:@", logo='"])) appendWithNSString:logo_])) appendWithChar:'\''];
  (void) [((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([sb appendWithNSString:@", background='"])) appendWithNSString:background_])) appendWithChar:'\''];
  (void) [((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([sb appendWithNSString:@", link='"])) appendWithNSString:link_])) appendWithChar:'\''];
  (void) [((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([sb appendWithNSString:@", cuisine='"])) appendWithNSString:cuisine_])) appendWithChar:'\''];
  (void) [((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([sb appendWithNSString:@", payment='"])) appendWithNSString:payment_])) appendWithChar:'\''];
  (void) [((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([sb appendWithNSString:@", shortDescription='"])) appendWithNSString:shortDescription_])) appendWithChar:'\''];
  (void) [((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([sb appendWithNSString:@", longDescription='"])) appendWithNSString:longDescription_])) appendWithChar:'\''];
  (void) [sb appendWithChar:'}'];
  return [sb description];
}

- (instancetype)init {
  return [super init];
}

- (void)copyAllFieldsTo:(ComBrianjmeltonFoodtruckrSharedVoRestaurant *)other {
  [super copyAllFieldsTo:other];
  other->name_ = name_;
  other->id__ = id__;
  other->logo_ = logo_;
  other->background_ = background_;
  other->link_ = link_;
  other->cuisine_ = cuisine_;
  other->payment_ = payment_;
  other->shortDescription_ = shortDescription_;
  other->longDescription_ = longDescription_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getName", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setNameWithNSString:", "setName", "V", 0x1, NULL },
    { "getId", NULL, "J", 0x1, NULL },
    { "setIdWithLong:", "setId", "V", 0x1, NULL },
    { "getLogo", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setLogoWithNSString:", "setLogo", "V", 0x1, NULL },
    { "getBackground", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setBackgroundWithNSString:", "setBackground", "V", 0x1, NULL },
    { "getLink", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setLinkWithNSString:", "setLink", "V", 0x1, NULL },
    { "getCuisine", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setCuisineWithNSString:", "setCuisine", "V", 0x1, NULL },
    { "getPayment", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setPaymentWithNSString:", "setPayment", "V", 0x1, NULL },
    { "getShortDescription", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setShortDescriptionWithNSString:", "setShortDescription", "V", 0x1, NULL },
    { "getLongDescription", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setLongDescriptionWithNSString:", "setLongDescription", "V", 0x1, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "name_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
    { "id__", "id", 0x2, "J", NULL,  },
    { "logo_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
    { "background_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
    { "link_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
    { "cuisine_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
    { "payment_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
    { "shortDescription_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
    { "longDescription_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
  };
  static const J2ObjcClassInfo _ComBrianjmeltonFoodtruckrSharedVoRestaurant = { "Restaurant", "com.brianjmelton.foodtruckr.shared.vo", NULL, 0x1, 20, methods, 9, fields, 0, NULL};
  return &_ComBrianjmeltonFoodtruckrSharedVoRestaurant;
}

@end
