//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Android/FoodTruckr/app/src/main/java/com/brianjmelton/foodtruckr/shared/list/RestaurantListDelegate.java
//

#ifndef _ComBrianjmeltonFoodtruckrSharedListRestaurantListDelegate_H_
#define _ComBrianjmeltonFoodtruckrSharedListRestaurantListDelegate_H_

#import "JreEmulation.h"

@protocol ComBrianjmeltonFoodtruckrSharedListRestaurantListDelegate < NSObject, JavaObject >

- (void)onRestaurantClickedWithLong:(jlong)id_;

@end

__attribute__((always_inline)) inline void ComBrianjmeltonFoodtruckrSharedListRestaurantListDelegate_init() {}

#endif // _ComBrianjmeltonFoodtruckrSharedListRestaurantListDelegate_H_
