//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Android/FoodTruckr/app/src/main/java/com/brianjmelton/foodtruckr/shared/list/RestaurantListDispatch.java
//

#include "com/brianjmelton/foodtruckr/shared/list/RestaurantListDispatch.h"

@interface ComBrianjmeltonFoodtruckrSharedListRestaurantListDispatch : NSObject
@end

@implementation ComBrianjmeltonFoodtruckrSharedListRestaurantListDispatch

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "onShowRestaurantDetailWithLong:", "onShowRestaurantDetail", "V", 0x401, NULL },
  };
  static const J2ObjcClassInfo _ComBrianjmeltonFoodtruckrSharedListRestaurantListDispatch = { "RestaurantListDispatch", "com.brianjmelton.foodtruckr.shared.list", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_ComBrianjmeltonFoodtruckrSharedListRestaurantListDispatch;
}

@end

