//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Android/FoodTruckr/app/src/main/java/com/brianjmelton/foodtruckr/shared/list/RestaurantListDispatch.java
//

#ifndef _ComBrianjmeltonFoodtruckrSharedListRestaurantListDispatch_H_
#define _ComBrianjmeltonFoodtruckrSharedListRestaurantListDispatch_H_

#import "JreEmulation.h"

@protocol ComBrianjmeltonFoodtruckrSharedListRestaurantListDispatch < NSObject, JavaObject >

- (void)onShowRestaurantDetailWithLong:(jlong)id_;

@end

__attribute__((always_inline)) inline void ComBrianjmeltonFoodtruckrSharedListRestaurantListDispatch_init() {}

#endif // _ComBrianjmeltonFoodtruckrSharedListRestaurantListDispatch_H_
