//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Android/FoodTruckr/app/src/main/java/com/brianjmelton/foodtruckr/shared/list/RestaurantListDelegate.java
//

#include "com/brianjmelton/foodtruckr/shared/list/RestaurantListDelegate.h"

@interface ComBrianjmeltonFoodtruckrSharedListRestaurantListDelegate : NSObject
@end

@implementation ComBrianjmeltonFoodtruckrSharedListRestaurantListDelegate

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "onRestaurantClickedWithLong:", "onRestaurantClicked", "V", 0x401, NULL },
  };
  static const J2ObjcClassInfo _ComBrianjmeltonFoodtruckrSharedListRestaurantListDelegate = { "RestaurantListDelegate", "com.brianjmelton.foodtruckr.shared.list", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_ComBrianjmeltonFoodtruckrSharedListRestaurantListDelegate;
}

@end

